CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username varchar(80) UNIQUE NOT NULL,
  email varchar(160) UNIQUE NOT NULL, password_hash varchar(255) NOT NULL,
  avatar text DEFAULT '', bio text DEFAULT '', level integer DEFAULT 1,
  level_title varchar(80) DEFAULT '初级学习者', learning_days integer DEFAULT 1,
  created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS refresh_tokens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, token_hash varchar(128) UNIQUE NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS courses (id bigserial PRIMARY KEY, title varchar(240) NOT NULL, category varchar(40), category_label varchar(40), difficulty varchar(30), level varchar(30), status varchar(30) DEFAULT 'not_started', cover_image text, summary text, description text, author varchar(100), publish_date varchar(50), read_time varchar(30), views integer DEFAULT 0, tags jsonb DEFAULT '[]', sections jsonb DEFAULT '[]', lessons_count integer DEFAULT 0, estimated_hours integer DEFAULT 0, progress integer DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_courses_category ON courses(category);
CREATE TABLE IF NOT EXISTS comments (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), course_id bigint REFERENCES courses(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, content text NOT NULL, likes integer DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS course_likes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), course_id bigint REFERENCES courses(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz DEFAULT now(), UNIQUE(course_id,user_id));
CREATE TABLE IF NOT EXISTS favorites (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), course_id bigint REFERENCES courses(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, created_at timestamptz DEFAULT now(), UNIQUE(course_id,user_id));
CREATE TABLE IF NOT EXISTS notes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), course_id bigint REFERENCES courses(id) ON DELETE CASCADE, user_id uuid REFERENCES users(id) ON DELETE CASCADE, title text NOT NULL, content text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS problems (id bigserial PRIMARY KEY, title varchar(240), category varchar(60), difficulty varchar(30), description text, examples jsonb DEFAULT '[]', constraints jsonb DEFAULT '[]', tags jsonb DEFAULT '[]', templates jsonb DEFAULT '{}', test_cases jsonb DEFAULT '[]', pass_rate double precision DEFAULT 0, submissions integer DEFAULT 0, status varchar(30) DEFAULT 'not_started', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS submissions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, problem_id bigint REFERENCES problems(id) ON DELETE CASCADE, language text, code text, status text, passed_cases integer DEFAULT 0, total_cases integer DEFAULT 0, execution_time_ms bigint DEFAULT 0, memory_kb bigint DEFAULT 0, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS learning_progresses (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, course_id bigint REFERENCES courses(id) ON DELETE CASCADE, progress integer DEFAULT 0 CHECK(progress BETWEEN 0 AND 100), last_section_id text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), UNIQUE(user_id,course_id));
CREATE TABLE IF NOT EXISTS daily_study_times (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, course_id bigint, study_date date NOT NULL, duration_minutes integer DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS learning_paths (id varchar(40) PRIMARY KEY, name text, description text, courses integer DEFAULT 0, levels integer DEFAULT 0, icon text, color text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS learning_path_stages (id varchar(50) PRIMARY KEY, path_id varchar(40) REFERENCES learning_paths(id) ON DELETE CASCADE, name text, status text, hours integer DEFAULT 0, goal text, courses jsonb DEFAULT '[]', prerequisite text, sort_order integer DEFAULT 0);
CREATE TABLE IF NOT EXISTS resume_templates (id varchar(60) PRIMARY KEY, name text, category text, description text, preview text, sections jsonb DEFAULT '[]', style text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS resumes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, filename text, object_key text, file_size bigint, mime_type text, analysis_json jsonb DEFAULT '{}', optimized_content text, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, name text, description text, tech_stack jsonb DEFAULT '[]', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS project_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid REFERENCES projects(id) ON DELETE CASCADE, title text, description text, status text DEFAULT 'pending', files jsonb DEFAULT '[]', analysis text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS interview_exams (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, direction text, difficulty text, questions jsonb DEFAULT '[]', score integer DEFAULT 0, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS session_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, session_id uuid NOT NULL, role text, agent text, content text, workflow_json jsonb DEFAULT '{}', created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS user_tool_settings (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, tool_id varchar(60), enabled boolean DEFAULT true, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now(), UNIQUE(user_id,tool_id));
CREATE TABLE IF NOT EXISTS user_profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE REFERENCES users(id) ON DELETE CASCADE, level text, focus_areas jsonb DEFAULT '[]', weak_areas jsonb DEFAULT '[]', learning_style text, preferred_difficulty text, daily_goal integer DEFAULT 30, total_study_time integer DEFAULT 0, streak integer DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS user_knowledge_graphs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid UNIQUE REFERENCES users(id) ON DELETE CASCADE, areas jsonb DEFAULT '[]', recent_topics jsonb DEFAULT '[]', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS workflow_executions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, status text, current_node text, input_json jsonb DEFAULT '{}', result_json jsonb DEFAULT '{}', created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS user_activities (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, type text, text text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS achievements (id varchar(60) PRIMARY KEY, name text, description text, icon text, created_at timestamptz DEFAULT now());
CREATE TABLE IF NOT EXISTS user_achievements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid REFERENCES users(id) ON DELETE CASCADE, achievement_id varchar(60) REFERENCES achievements(id) ON DELETE CASCADE, unlocked_at timestamptz, UNIQUE(user_id,achievement_id));
